### PR TITLE
2014 Website Proposal

### PR DESCRIPTION
**Pull request by girafe**
Hello accessibilafficiandos.

This is an unfinished proposal for the the 2014 Ottawa Accessibility Unconference website. You can preview the site at https://girafe.github.io/accessibilityunconference/

I am not sure if this kind of uninvited design proposal will be received well. If you don’t have any interest in it I will remove the pull request and step off. I don’t mean to step on any toes.

If this is a proposal you might consider I would be pleased to hear any suggestions and comments.

### CODE REVIEW

**Comment by nschonni** [comment]
@girafe that looks great! Unfortunately we are currently trying to align our site with the other a11y camp websites.
I think there is probably a bunch of the text copy that we can use.

PS: I'm guessing there would also be contrast issues with the top image/text overlay.

**Comment by girafe** [comment]
Thanks for the feedback @nschonni

Can you elaborate on the "contrast issues" you mentioned? I don’t understand what the issue would be and I don’t understand why you are guessing.

**Comment by nschonni** [comment]
http://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html
I'm guessing because I didn't want to go down the route of actually running a contrast check.

**Comment by girafe** [comment]
I see. Thanks.

The contract ratio of the type on the cover is better than 0.5. And it’s overlaid on of a background of desaturated natural tones so I don’t anticipate it would be too problematic for animal eyes.

**Comment by girafe** [comment]
Why is it necessary for the Ottawa chapter to conform to a foreign aesthetic, layout and program?

What is the advantage of conformity in this case?

I see no advantage myself.

**Pull request closed without merging**
